version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: subscription_tracker_db
    environment:
      POSTGRES_DB: subscription_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - subscription_tracker_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subscription_tracker_api
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - subscription_tracker_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  subscription_tracker_network:
    driver: bridge